version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
          - deps-{{ checksum "bower.json" }}-{{ checksum "package.json" }}

      - run:
          command: |
            yarn add --dev bower purescript pulp
            yarn
            yarn build
            git checkout -- package.json

      - save_cache:
          paths:
            - node_modules
            - bower_components
            - output
          key: deps-{{ checksum "bower.json" }}-{{ checksum "package.json" }}

      - run:
          command: yarn jest

workflows:
  version: 2
  build-test:
    jobs:
      - test
